# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modoboa_alias_pipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliaspipe',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aliaspipe',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
